### ISSUE TITLE
how to get the position of hovered residue then highlight next residue in html

### ISSUE THREAD

**Issue by orangeSi** [molstar/rcsb-molstar#11]
```
!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <div id="viewer"></div>
        <script type="text/javascript" src="./rcsb-molstar.js"></script>
        <script type="text/javascript">
  
            // create an instance of the plugin
            const viewer = new rcsbMolstar.Viewer('viewer', { })

            // load pdbId or url
            viewer.loadPdbId("1CRN");
            
            // here how to [ listen hover event to get the position of hovered residue then highlight next residue ] ? 

        </script>
    </body>
</html>
```

thanks~
Si

**Comment by orangeSi** [comment]
I saw the tutorial in https://github.com/molstar/rcsb-molstar/blob/master/src/viewer/index.html, but I  still don't know how to get the  position of hovered residue then highlight next residue .

**Comment by orangeSi** [comment]
@JonStargaryen

**Comment by JonStargaryen** [comment]
rcsb-molstar isn't the best library to achieve this, it's mainly implementing functionality/behaviors specific to RCSB.org and isn't tremendously useful as general purpose dependency.

I'd go with the main Mol* library and follow David's and rtviii's comments from https://github.com/molstar/molstar/issues/1001#issuecomment-1848939354.
